// Code generated by "make build"; DO NOT EDIT.

package iso3166

type ISO31661Alpha2 string

func (i ISO31661Alpha2) String() string {
	return string(i)
}

const (
	// Taiwan
	TW ISO31661Alpha3 = "TW"
	// Afghanistan
	AF ISO31661Alpha3 = "AF"
	// Albania
	AL ISO31661Alpha3 = "AL"
	// Algeria
	DZ ISO31661Alpha3 = "DZ"
	// American Samoa
	AS ISO31661Alpha3 = "AS"
	// Andorra
	AD ISO31661Alpha3 = "AD"
	// Angola
	AO ISO31661Alpha3 = "AO"
	// Anguilla
	AI ISO31661Alpha3 = "AI"
	// Antarctica
	AQ ISO31661Alpha3 = "AQ"
	// Antigua & Barbuda
	AG ISO31661Alpha3 = "AG"
	// Argentina
	AR ISO31661Alpha3 = "AR"
	// Armenia
	AM ISO31661Alpha3 = "AM"
	// Aruba
	AW ISO31661Alpha3 = "AW"
	// Australia
	AU ISO31661Alpha3 = "AU"
	// Austria
	AT ISO31661Alpha3 = "AT"
	// Azerbaijan
	AZ ISO31661Alpha3 = "AZ"
	// Bahamas
	BS ISO31661Alpha3 = "BS"
	// Bahrain
	BH ISO31661Alpha3 = "BH"
	// Bangladesh
	BD ISO31661Alpha3 = "BD"
	// Barbados
	BB ISO31661Alpha3 = "BB"
	// Belarus
	BY ISO31661Alpha3 = "BY"
	// Belgium
	BE ISO31661Alpha3 = "BE"
	// Belize
	BZ ISO31661Alpha3 = "BZ"
	// Benin
	BJ ISO31661Alpha3 = "BJ"
	// Bermuda
	BM ISO31661Alpha3 = "BM"
	// Bhutan
	BT ISO31661Alpha3 = "BT"
	// Bolivia
	BO ISO31661Alpha3 = "BO"
	// Caribbean Netherlands
	BQ ISO31661Alpha3 = "BQ"
	// Bosnia
	BA ISO31661Alpha3 = "BA"
	// Botswana
	BW ISO31661Alpha3 = "BW"
	// Bouvet Island
	BV ISO31661Alpha3 = "BV"
	// Brazil
	BR ISO31661Alpha3 = "BR"
	// British Indian Ocean Territory
	IO ISO31661Alpha3 = "IO"
	// British Virgin Islands
	VG ISO31661Alpha3 = "VG"
	// Brunei
	BN ISO31661Alpha3 = "BN"
	// Bulgaria
	BG ISO31661Alpha3 = "BG"
	// Burkina Faso
	BF ISO31661Alpha3 = "BF"
	// Burundi
	BI ISO31661Alpha3 = "BI"
	// Cape Verde
	CV ISO31661Alpha3 = "CV"
	// Cambodia
	KH ISO31661Alpha3 = "KH"
	// Cameroon
	CM ISO31661Alpha3 = "CM"
	// Canada
	CA ISO31661Alpha3 = "CA"
	// Cayman Islands
	KY ISO31661Alpha3 = "KY"
	// Central African Republic
	CF ISO31661Alpha3 = "CF"
	// Chad
	TD ISO31661Alpha3 = "TD"
	// Chile
	CL ISO31661Alpha3 = "CL"
	// China
	CN ISO31661Alpha3 = "CN"
	// Hong Kong
	HK ISO31661Alpha3 = "HK"
	// Macau
	MO ISO31661Alpha3 = "MO"
	// Christmas Island
	CX ISO31661Alpha3 = "CX"
	// Cocos (Keeling) Islands
	CC ISO31661Alpha3 = "CC"
	// Colombia
	CO ISO31661Alpha3 = "CO"
	// Comoros
	KM ISO31661Alpha3 = "KM"
	// Congo - Brazzaville
	CG ISO31661Alpha3 = "CG"
	// Cook Islands
	CK ISO31661Alpha3 = "CK"
	// Costa Rica
	CR ISO31661Alpha3 = "CR"
	// Croatia
	HR ISO31661Alpha3 = "HR"
	// Cuba
	CU ISO31661Alpha3 = "CU"
	// Curaçao
	CW ISO31661Alpha3 = "CW"
	// Cyprus
	CY ISO31661Alpha3 = "CY"
	// Czechia
	CZ ISO31661Alpha3 = "CZ"
	// Côte d’Ivoire
	CI ISO31661Alpha3 = "CI"
	// North Korea
	KP ISO31661Alpha3 = "KP"
	// Congo - Kinshasa
	CD ISO31661Alpha3 = "CD"
	// Denmark
	DK ISO31661Alpha3 = "DK"
	// Djibouti
	DJ ISO31661Alpha3 = "DJ"
	// Dominica
	DM ISO31661Alpha3 = "DM"
	// Dominican Republic
	DO ISO31661Alpha3 = "DO"
	// Ecuador
	EC ISO31661Alpha3 = "EC"
	// Egypt
	EG ISO31661Alpha3 = "EG"
	// El Salvador
	SV ISO31661Alpha3 = "SV"
	// Equatorial Guinea
	GQ ISO31661Alpha3 = "GQ"
	// Eritrea
	ER ISO31661Alpha3 = "ER"
	// Estonia
	EE ISO31661Alpha3 = "EE"
	// Ethiopia
	ET ISO31661Alpha3 = "ET"
	// Falkland Islands
	FK ISO31661Alpha3 = "FK"
	// Faroe Islands
	FO ISO31661Alpha3 = "FO"
	// Fiji
	FJ ISO31661Alpha3 = "FJ"
	// Finland
	FI ISO31661Alpha3 = "FI"
	// France
	FR ISO31661Alpha3 = "FR"
	// French Guiana
	GF ISO31661Alpha3 = "GF"
	// French Polynesia
	PF ISO31661Alpha3 = "PF"
	// French Southern Territories
	TF ISO31661Alpha3 = "TF"
	// Gabon
	GA ISO31661Alpha3 = "GA"
	// Gambia
	GM ISO31661Alpha3 = "GM"
	// Georgia
	GE ISO31661Alpha3 = "GE"
	// Germany
	DE ISO31661Alpha3 = "DE"
	// Ghana
	GH ISO31661Alpha3 = "GH"
	// Gibraltar
	GI ISO31661Alpha3 = "GI"
	// Greece
	GR ISO31661Alpha3 = "GR"
	// Greenland
	GL ISO31661Alpha3 = "GL"
	// Grenada
	GD ISO31661Alpha3 = "GD"
	// Guadeloupe
	GP ISO31661Alpha3 = "GP"
	// Guam
	GU ISO31661Alpha3 = "GU"
	// Guatemala
	GT ISO31661Alpha3 = "GT"
	// Guernsey
	GG ISO31661Alpha3 = "GG"
	// Guinea
	GN ISO31661Alpha3 = "GN"
	// Guinea-Bissau
	GW ISO31661Alpha3 = "GW"
	// Guyana
	GY ISO31661Alpha3 = "GY"
	// Haiti
	HT ISO31661Alpha3 = "HT"
	// Heard & McDonald Islands
	HM ISO31661Alpha3 = "HM"
	// Vatican City
	VA ISO31661Alpha3 = "VA"
	// Honduras
	HN ISO31661Alpha3 = "HN"
	// Hungary
	HU ISO31661Alpha3 = "HU"
	// Iceland
	IS ISO31661Alpha3 = "IS"
	// India
	IN ISO31661Alpha3 = "IN"
	// Indonesia
	ID ISO31661Alpha3 = "ID"
	// Iran
	IR ISO31661Alpha3 = "IR"
	// Iraq
	IQ ISO31661Alpha3 = "IQ"
	// Ireland
	IE ISO31661Alpha3 = "IE"
	// Isle of Man
	IM ISO31661Alpha3 = "IM"
	// Israel
	IL ISO31661Alpha3 = "IL"
	// Italy
	IT ISO31661Alpha3 = "IT"
	// Jamaica
	JM ISO31661Alpha3 = "JM"
	// Japan
	JP ISO31661Alpha3 = "JP"
	// Jersey
	JE ISO31661Alpha3 = "JE"
	// Jordan
	JO ISO31661Alpha3 = "JO"
	// Kazakhstan
	KZ ISO31661Alpha3 = "KZ"
	// Kenya
	KE ISO31661Alpha3 = "KE"
	// Kiribati
	KI ISO31661Alpha3 = "KI"
	// Kuwait
	KW ISO31661Alpha3 = "KW"
	// Kyrgyzstan
	KG ISO31661Alpha3 = "KG"
	// Laos
	LA ISO31661Alpha3 = "LA"
	// Latvia
	LV ISO31661Alpha3 = "LV"
	// Lebanon
	LB ISO31661Alpha3 = "LB"
	// Lesotho
	LS ISO31661Alpha3 = "LS"
	// Liberia
	LR ISO31661Alpha3 = "LR"
	// Libya
	LY ISO31661Alpha3 = "LY"
	// Liechtenstein
	LI ISO31661Alpha3 = "LI"
	// Lithuania
	LT ISO31661Alpha3 = "LT"
	// Luxembourg
	LU ISO31661Alpha3 = "LU"
	// Madagascar
	MG ISO31661Alpha3 = "MG"
	// Malawi
	MW ISO31661Alpha3 = "MW"
	// Malaysia
	MY ISO31661Alpha3 = "MY"
	// Maldives
	MV ISO31661Alpha3 = "MV"
	// Mali
	ML ISO31661Alpha3 = "ML"
	// Malta
	MT ISO31661Alpha3 = "MT"
	// Marshall Islands
	MH ISO31661Alpha3 = "MH"
	// Martinique
	MQ ISO31661Alpha3 = "MQ"
	// Mauritania
	MR ISO31661Alpha3 = "MR"
	// Mauritius
	MU ISO31661Alpha3 = "MU"
	// Mayotte
	YT ISO31661Alpha3 = "YT"
	// Mexico
	MX ISO31661Alpha3 = "MX"
	// Micronesia
	FM ISO31661Alpha3 = "FM"
	// Monaco
	MC ISO31661Alpha3 = "MC"
	// Mongolia
	MN ISO31661Alpha3 = "MN"
	// Montenegro
	ME ISO31661Alpha3 = "ME"
	// Montserrat
	MS ISO31661Alpha3 = "MS"
	// Morocco
	MA ISO31661Alpha3 = "MA"
	// Mozambique
	MZ ISO31661Alpha3 = "MZ"
	// Myanmar
	MM ISO31661Alpha3 = "MM"
	// Namibia
	NA ISO31661Alpha3 = "NA"
	// Nauru
	NR ISO31661Alpha3 = "NR"
	// Nepal
	NP ISO31661Alpha3 = "NP"
	// Netherlands
	NL ISO31661Alpha3 = "NL"
	// New Caledonia
	NC ISO31661Alpha3 = "NC"
	// New Zealand
	NZ ISO31661Alpha3 = "NZ"
	// Nicaragua
	NI ISO31661Alpha3 = "NI"
	// Niger
	NE ISO31661Alpha3 = "NE"
	// Nigeria
	NG ISO31661Alpha3 = "NG"
	// Niue
	NU ISO31661Alpha3 = "NU"
	// Norfolk Island
	NF ISO31661Alpha3 = "NF"
	// Northern Mariana Islands
	MP ISO31661Alpha3 = "MP"
	// Norway
	NO ISO31661Alpha3 = "NO"
	// Oman
	OM ISO31661Alpha3 = "OM"
	// Pakistan
	PK ISO31661Alpha3 = "PK"
	// Palau
	PW ISO31661Alpha3 = "PW"
	// Panama
	PA ISO31661Alpha3 = "PA"
	// Papua New Guinea
	PG ISO31661Alpha3 = "PG"
	// Paraguay
	PY ISO31661Alpha3 = "PY"
	// Peru
	PE ISO31661Alpha3 = "PE"
	// Philippines
	PH ISO31661Alpha3 = "PH"
	// Pitcairn Islands
	PN ISO31661Alpha3 = "PN"
	// Poland
	PL ISO31661Alpha3 = "PL"
	// Portugal
	PT ISO31661Alpha3 = "PT"
	// Puerto Rico
	PR ISO31661Alpha3 = "PR"
	// Qatar
	QA ISO31661Alpha3 = "QA"
	// South Korea
	KR ISO31661Alpha3 = "KR"
	// Moldova
	MD ISO31661Alpha3 = "MD"
	// Romania
	RO ISO31661Alpha3 = "RO"
	// Russia
	RU ISO31661Alpha3 = "RU"
	// Rwanda
	RW ISO31661Alpha3 = "RW"
	// Réunion
	RE ISO31661Alpha3 = "RE"
	// St. Barthélemy
	BL ISO31661Alpha3 = "BL"
	// St. Helena
	SH ISO31661Alpha3 = "SH"
	// St. Kitts & Nevis
	KN ISO31661Alpha3 = "KN"
	// St. Lucia
	LC ISO31661Alpha3 = "LC"
	// St. Martin
	MF ISO31661Alpha3 = "MF"
	// St. Pierre & Miquelon
	PM ISO31661Alpha3 = "PM"
	// St. Vincent & Grenadines
	VC ISO31661Alpha3 = "VC"
	// Samoa
	WS ISO31661Alpha3 = "WS"
	// San Marino
	SM ISO31661Alpha3 = "SM"
	// São Tomé & Príncipe
	ST ISO31661Alpha3 = "ST"
	// Saudi Arabia
	SA ISO31661Alpha3 = "SA"
	// Senegal
	SN ISO31661Alpha3 = "SN"
	// Serbia
	RS ISO31661Alpha3 = "RS"
	// Seychelles
	SC ISO31661Alpha3 = "SC"
	// Sierra Leone
	SL ISO31661Alpha3 = "SL"
	// Singapore
	SG ISO31661Alpha3 = "SG"
	// Sint Maarten
	SX ISO31661Alpha3 = "SX"
	// Slovakia
	SK ISO31661Alpha3 = "SK"
	// Slovenia
	SI ISO31661Alpha3 = "SI"
	// Solomon Islands
	SB ISO31661Alpha3 = "SB"
	// Somalia
	SO ISO31661Alpha3 = "SO"
	// South Africa
	ZA ISO31661Alpha3 = "ZA"
	// South Georgia & South Sandwich Islands
	GS ISO31661Alpha3 = "GS"
	// South Sudan
	SS ISO31661Alpha3 = "SS"
	// Spain
	ES ISO31661Alpha3 = "ES"
	// Sri Lanka
	LK ISO31661Alpha3 = "LK"
	// Palestine
	PS ISO31661Alpha3 = "PS"
	// Sudan
	SD ISO31661Alpha3 = "SD"
	// Suriname
	SR ISO31661Alpha3 = "SR"
	// Svalbard & Jan Mayen
	SJ ISO31661Alpha3 = "SJ"
	// Swaziland
	SZ ISO31661Alpha3 = "SZ"
	// Sweden
	SE ISO31661Alpha3 = "SE"
	// Switzerland
	CH ISO31661Alpha3 = "CH"
	// Syria
	SY ISO31661Alpha3 = "SY"
	// Tajikistan
	TJ ISO31661Alpha3 = "TJ"
	// Thailand
	TH ISO31661Alpha3 = "TH"
	// Macedonia
	MK ISO31661Alpha3 = "MK"
	// Timor-Leste
	TL ISO31661Alpha3 = "TL"
	// Togo
	TG ISO31661Alpha3 = "TG"
	// Tokelau
	TK ISO31661Alpha3 = "TK"
	// Tonga
	TO ISO31661Alpha3 = "TO"
	// Trinidad & Tobago
	TT ISO31661Alpha3 = "TT"
	// Tunisia
	TN ISO31661Alpha3 = "TN"
	// Turkey
	TR ISO31661Alpha3 = "TR"
	// Turkmenistan
	TM ISO31661Alpha3 = "TM"
	// Turks & Caicos Islands
	TC ISO31661Alpha3 = "TC"
	// Tuvalu
	TV ISO31661Alpha3 = "TV"
	// Uganda
	UG ISO31661Alpha3 = "UG"
	// Ukraine
	UA ISO31661Alpha3 = "UA"
	// United Arab Emirates
	AE ISO31661Alpha3 = "AE"
	// UK
	GB ISO31661Alpha3 = "GB"
	// Tanzania
	TZ ISO31661Alpha3 = "TZ"
	// U.S. Outlying Islands
	UM ISO31661Alpha3 = "UM"
	// U.S. Virgin Islands
	VI ISO31661Alpha3 = "VI"
	// US
	US ISO31661Alpha3 = "US"
	// Uruguay
	UY ISO31661Alpha3 = "UY"
	// Uzbekistan
	UZ ISO31661Alpha3 = "UZ"
	// Vanuatu
	VU ISO31661Alpha3 = "VU"
	// Venezuela
	VE ISO31661Alpha3 = "VE"
	// Vietnam
	VN ISO31661Alpha3 = "VN"
	// Wallis & Futuna
	WF ISO31661Alpha3 = "WF"
	// Western Sahara
	EH ISO31661Alpha3 = "EH"
	// Yemen
	YE ISO31661Alpha3 = "YE"
	// Zambia
	ZM ISO31661Alpha3 = "ZM"
	// Zimbabwe
	ZW ISO31661Alpha3 = "ZW"
	// Åland Islands
	AX ISO31661Alpha3 = "AX"
)

var ValidAlpha2Codes = []ISO31661Alpha2{
	TW,
	AF,
	AL,
	DZ,
	AS,
	AD,
	AO,
	AI,
	AQ,
	AG,
	AR,
	AM,
	AW,
	AU,
	AT,
	AZ,
	BS,
	BH,
	BD,
	BB,
	BY,
	BE,
	BZ,
	BJ,
	BM,
	BT,
	BO,
	BQ,
	BA,
	BW,
	BV,
	BR,
	IO,
	VG,
	BN,
	BG,
	BF,
	BI,
	CV,
	KH,
	CM,
	CA,
	KY,
	CF,
	TD,
	CL,
	CN,
	HK,
	MO,
	CX,
	CC,
	CO,
	KM,
	CG,
	CK,
	CR,
	HR,
	CU,
	CW,
	CY,
	CZ,
	CI,
	KP,
	CD,
	DK,
	DJ,
	DM,
	DO,
	EC,
	EG,
	SV,
	GQ,
	ER,
	EE,
	ET,
	FK,
	FO,
	FJ,
	FI,
	FR,
	GF,
	PF,
	TF,
	GA,
	GM,
	GE,
	DE,
	GH,
	GI,
	GR,
	GL,
	GD,
	GP,
	GU,
	GT,
	GG,
	GN,
	GW,
	GY,
	HT,
	HM,
	VA,
	HN,
	HU,
	IS,
	IN,
	ID,
	IR,
	IQ,
	IE,
	IM,
	IL,
	IT,
	JM,
	JP,
	JE,
	JO,
	KZ,
	KE,
	KI,
	KW,
	KG,
	LA,
	LV,
	LB,
	LS,
	LR,
	LY,
	LI,
	LT,
	LU,
	MG,
	MW,
	MY,
	MV,
	ML,
	MT,
	MH,
	MQ,
	MR,
	MU,
	YT,
	MX,
	FM,
	MC,
	MN,
	ME,
	MS,
	MA,
	MZ,
	MM,
	NA,
	NR,
	NP,
	NL,
	NC,
	NZ,
	NI,
	NE,
	NG,
	NU,
	NF,
	MP,
	NO,
	OM,
	PK,
	PW,
	PA,
	PG,
	PY,
	PE,
	PH,
	PN,
	PL,
	PT,
	PR,
	QA,
	KR,
	MD,
	RO,
	RU,
	RW,
	RE,
	BL,
	SH,
	KN,
	LC,
	MF,
	PM,
	VC,
	WS,
	SM,
	ST,
	SA,
	SN,
	RS,
	SC,
	SL,
	SG,
	SX,
	SK,
	SI,
	SB,
	SO,
	ZA,
	GS,
	SS,
	ES,
	LK,
	PS,
	SD,
	SR,
	SJ,
	SZ,
	SE,
	CH,
	SY,
	TJ,
	TH,
	MK,
	TL,
	TG,
	TK,
	TO,
	TT,
	TN,
	TR,
	TM,
	TC,
	TV,
	UG,
	UA,
	AE,
	GB,
	TZ,
	UM,
	VI,
	US,
	UY,
	UZ,
	VU,
	VE,
	VN,
	WF,
	EH,
	YE,
	ZM,
	ZW,
	AX,
}

type ISO31661Alpha3 string

func (i ISO31661Alpha3) String() string {
	return string(i)
}

const (
	// Taiwan
	TWN ISO31661Alpha3 = "TWN"
	// Afghanistan
	AFG ISO31661Alpha3 = "AFG"
	// Albania
	ALB ISO31661Alpha3 = "ALB"
	// Algeria
	DZA ISO31661Alpha3 = "DZA"
	// American Samoa
	ASM ISO31661Alpha3 = "ASM"
	// Andorra
	AND ISO31661Alpha3 = "AND"
	// Angola
	AGO ISO31661Alpha3 = "AGO"
	// Anguilla
	AIA ISO31661Alpha3 = "AIA"
	// Antarctica
	ATA ISO31661Alpha3 = "ATA"
	// Antigua & Barbuda
	ATG ISO31661Alpha3 = "ATG"
	// Argentina
	ARG ISO31661Alpha3 = "ARG"
	// Armenia
	ARM ISO31661Alpha3 = "ARM"
	// Aruba
	ABW ISO31661Alpha3 = "ABW"
	// Australia
	AUS ISO31661Alpha3 = "AUS"
	// Austria
	AUT ISO31661Alpha3 = "AUT"
	// Azerbaijan
	AZE ISO31661Alpha3 = "AZE"
	// Bahamas
	BHS ISO31661Alpha3 = "BHS"
	// Bahrain
	BHR ISO31661Alpha3 = "BHR"
	// Bangladesh
	BGD ISO31661Alpha3 = "BGD"
	// Barbados
	BRB ISO31661Alpha3 = "BRB"
	// Belarus
	BLR ISO31661Alpha3 = "BLR"
	// Belgium
	BEL ISO31661Alpha3 = "BEL"
	// Belize
	BLZ ISO31661Alpha3 = "BLZ"
	// Benin
	BEN ISO31661Alpha3 = "BEN"
	// Bermuda
	BMU ISO31661Alpha3 = "BMU"
	// Bhutan
	BTN ISO31661Alpha3 = "BTN"
	// Bolivia
	BOL ISO31661Alpha3 = "BOL"
	// Caribbean Netherlands
	BES ISO31661Alpha3 = "BES"
	// Bosnia
	BIH ISO31661Alpha3 = "BIH"
	// Botswana
	BWA ISO31661Alpha3 = "BWA"
	// Bouvet Island
	BVT ISO31661Alpha3 = "BVT"
	// Brazil
	BRA ISO31661Alpha3 = "BRA"
	// British Indian Ocean Territory
	IOT ISO31661Alpha3 = "IOT"
	// British Virgin Islands
	VGB ISO31661Alpha3 = "VGB"
	// Brunei
	BRN ISO31661Alpha3 = "BRN"
	// Bulgaria
	BGR ISO31661Alpha3 = "BGR"
	// Burkina Faso
	BFA ISO31661Alpha3 = "BFA"
	// Burundi
	BDI ISO31661Alpha3 = "BDI"
	// Cape Verde
	CPV ISO31661Alpha3 = "CPV"
	// Cambodia
	KHM ISO31661Alpha3 = "KHM"
	// Cameroon
	CMR ISO31661Alpha3 = "CMR"
	// Canada
	CAN ISO31661Alpha3 = "CAN"
	// Cayman Islands
	CYM ISO31661Alpha3 = "CYM"
	// Central African Republic
	CAF ISO31661Alpha3 = "CAF"
	// Chad
	TCD ISO31661Alpha3 = "TCD"
	// Chile
	CHL ISO31661Alpha3 = "CHL"
	// China
	CHN ISO31661Alpha3 = "CHN"
	// Hong Kong
	HKG ISO31661Alpha3 = "HKG"
	// Macau
	MAC ISO31661Alpha3 = "MAC"
	// Christmas Island
	CXR ISO31661Alpha3 = "CXR"
	// Cocos (Keeling) Islands
	CCK ISO31661Alpha3 = "CCK"
	// Colombia
	COL ISO31661Alpha3 = "COL"
	// Comoros
	COM ISO31661Alpha3 = "COM"
	// Congo - Brazzaville
	COG ISO31661Alpha3 = "COG"
	// Cook Islands
	COK ISO31661Alpha3 = "COK"
	// Costa Rica
	CRI ISO31661Alpha3 = "CRI"
	// Croatia
	HRV ISO31661Alpha3 = "HRV"
	// Cuba
	CUB ISO31661Alpha3 = "CUB"
	// Curaçao
	CUW ISO31661Alpha3 = "CUW"
	// Cyprus
	CYP ISO31661Alpha3 = "CYP"
	// Czechia
	CZE ISO31661Alpha3 = "CZE"
	// Côte d’Ivoire
	CIV ISO31661Alpha3 = "CIV"
	// North Korea
	PRK ISO31661Alpha3 = "PRK"
	// Congo - Kinshasa
	COD ISO31661Alpha3 = "COD"
	// Denmark
	DNK ISO31661Alpha3 = "DNK"
	// Djibouti
	DJI ISO31661Alpha3 = "DJI"
	// Dominica
	DMA ISO31661Alpha3 = "DMA"
	// Dominican Republic
	DOM ISO31661Alpha3 = "DOM"
	// Ecuador
	ECU ISO31661Alpha3 = "ECU"
	// Egypt
	EGY ISO31661Alpha3 = "EGY"
	// El Salvador
	SLV ISO31661Alpha3 = "SLV"
	// Equatorial Guinea
	GNQ ISO31661Alpha3 = "GNQ"
	// Eritrea
	ERI ISO31661Alpha3 = "ERI"
	// Estonia
	EST ISO31661Alpha3 = "EST"
	// Ethiopia
	ETH ISO31661Alpha3 = "ETH"
	// Falkland Islands
	FLK ISO31661Alpha3 = "FLK"
	// Faroe Islands
	FRO ISO31661Alpha3 = "FRO"
	// Fiji
	FJI ISO31661Alpha3 = "FJI"
	// Finland
	FIN ISO31661Alpha3 = "FIN"
	// France
	FRA ISO31661Alpha3 = "FRA"
	// French Guiana
	GUF ISO31661Alpha3 = "GUF"
	// French Polynesia
	PYF ISO31661Alpha3 = "PYF"
	// French Southern Territories
	ATF ISO31661Alpha3 = "ATF"
	// Gabon
	GAB ISO31661Alpha3 = "GAB"
	// Gambia
	GMB ISO31661Alpha3 = "GMB"
	// Georgia
	GEO ISO31661Alpha3 = "GEO"
	// Germany
	DEU ISO31661Alpha3 = "DEU"
	// Ghana
	GHA ISO31661Alpha3 = "GHA"
	// Gibraltar
	GIB ISO31661Alpha3 = "GIB"
	// Greece
	GRC ISO31661Alpha3 = "GRC"
	// Greenland
	GRL ISO31661Alpha3 = "GRL"
	// Grenada
	GRD ISO31661Alpha3 = "GRD"
	// Guadeloupe
	GLP ISO31661Alpha3 = "GLP"
	// Guam
	GUM ISO31661Alpha3 = "GUM"
	// Guatemala
	GTM ISO31661Alpha3 = "GTM"
	// Guernsey
	GGY ISO31661Alpha3 = "GGY"
	// Guinea
	GIN ISO31661Alpha3 = "GIN"
	// Guinea-Bissau
	GNB ISO31661Alpha3 = "GNB"
	// Guyana
	GUY ISO31661Alpha3 = "GUY"
	// Haiti
	HTI ISO31661Alpha3 = "HTI"
	// Heard & McDonald Islands
	HMD ISO31661Alpha3 = "HMD"
	// Vatican City
	VAT ISO31661Alpha3 = "VAT"
	// Honduras
	HND ISO31661Alpha3 = "HND"
	// Hungary
	HUN ISO31661Alpha3 = "HUN"
	// Iceland
	ISL ISO31661Alpha3 = "ISL"
	// India
	IND ISO31661Alpha3 = "IND"
	// Indonesia
	IDN ISO31661Alpha3 = "IDN"
	// Iran
	IRN ISO31661Alpha3 = "IRN"
	// Iraq
	IRQ ISO31661Alpha3 = "IRQ"
	// Ireland
	IRL ISO31661Alpha3 = "IRL"
	// Isle of Man
	IMN ISO31661Alpha3 = "IMN"
	// Israel
	ISR ISO31661Alpha3 = "ISR"
	// Italy
	ITA ISO31661Alpha3 = "ITA"
	// Jamaica
	JAM ISO31661Alpha3 = "JAM"
	// Japan
	JPN ISO31661Alpha3 = "JPN"
	// Jersey
	JEY ISO31661Alpha3 = "JEY"
	// Jordan
	JOR ISO31661Alpha3 = "JOR"
	// Kazakhstan
	KAZ ISO31661Alpha3 = "KAZ"
	// Kenya
	KEN ISO31661Alpha3 = "KEN"
	// Kiribati
	KIR ISO31661Alpha3 = "KIR"
	// Kuwait
	KWT ISO31661Alpha3 = "KWT"
	// Kyrgyzstan
	KGZ ISO31661Alpha3 = "KGZ"
	// Laos
	LAO ISO31661Alpha3 = "LAO"
	// Latvia
	LVA ISO31661Alpha3 = "LVA"
	// Lebanon
	LBN ISO31661Alpha3 = "LBN"
	// Lesotho
	LSO ISO31661Alpha3 = "LSO"
	// Liberia
	LBR ISO31661Alpha3 = "LBR"
	// Libya
	LBY ISO31661Alpha3 = "LBY"
	// Liechtenstein
	LIE ISO31661Alpha3 = "LIE"
	// Lithuania
	LTU ISO31661Alpha3 = "LTU"
	// Luxembourg
	LUX ISO31661Alpha3 = "LUX"
	// Madagascar
	MDG ISO31661Alpha3 = "MDG"
	// Malawi
	MWI ISO31661Alpha3 = "MWI"
	// Malaysia
	MYS ISO31661Alpha3 = "MYS"
	// Maldives
	MDV ISO31661Alpha3 = "MDV"
	// Mali
	MLI ISO31661Alpha3 = "MLI"
	// Malta
	MLT ISO31661Alpha3 = "MLT"
	// Marshall Islands
	MHL ISO31661Alpha3 = "MHL"
	// Martinique
	MTQ ISO31661Alpha3 = "MTQ"
	// Mauritania
	MRT ISO31661Alpha3 = "MRT"
	// Mauritius
	MUS ISO31661Alpha3 = "MUS"
	// Mayotte
	MYT ISO31661Alpha3 = "MYT"
	// Mexico
	MEX ISO31661Alpha3 = "MEX"
	// Micronesia
	FSM ISO31661Alpha3 = "FSM"
	// Monaco
	MCO ISO31661Alpha3 = "MCO"
	// Mongolia
	MNG ISO31661Alpha3 = "MNG"
	// Montenegro
	MNE ISO31661Alpha3 = "MNE"
	// Montserrat
	MSR ISO31661Alpha3 = "MSR"
	// Morocco
	MAR ISO31661Alpha3 = "MAR"
	// Mozambique
	MOZ ISO31661Alpha3 = "MOZ"
	// Myanmar
	MMR ISO31661Alpha3 = "MMR"
	// Namibia
	NAM ISO31661Alpha3 = "NAM"
	// Nauru
	NRU ISO31661Alpha3 = "NRU"
	// Nepal
	NPL ISO31661Alpha3 = "NPL"
	// Netherlands
	NLD ISO31661Alpha3 = "NLD"
	// New Caledonia
	NCL ISO31661Alpha3 = "NCL"
	// New Zealand
	NZL ISO31661Alpha3 = "NZL"
	// Nicaragua
	NIC ISO31661Alpha3 = "NIC"
	// Niger
	NER ISO31661Alpha3 = "NER"
	// Nigeria
	NGA ISO31661Alpha3 = "NGA"
	// Niue
	NIU ISO31661Alpha3 = "NIU"
	// Norfolk Island
	NFK ISO31661Alpha3 = "NFK"
	// Northern Mariana Islands
	MNP ISO31661Alpha3 = "MNP"
	// Norway
	NOR ISO31661Alpha3 = "NOR"
	// Oman
	OMN ISO31661Alpha3 = "OMN"
	// Pakistan
	PAK ISO31661Alpha3 = "PAK"
	// Palau
	PLW ISO31661Alpha3 = "PLW"
	// Panama
	PAN ISO31661Alpha3 = "PAN"
	// Papua New Guinea
	PNG ISO31661Alpha3 = "PNG"
	// Paraguay
	PRY ISO31661Alpha3 = "PRY"
	// Peru
	PER ISO31661Alpha3 = "PER"
	// Philippines
	PHL ISO31661Alpha3 = "PHL"
	// Pitcairn Islands
	PCN ISO31661Alpha3 = "PCN"
	// Poland
	POL ISO31661Alpha3 = "POL"
	// Portugal
	PRT ISO31661Alpha3 = "PRT"
	// Puerto Rico
	PRI ISO31661Alpha3 = "PRI"
	// Qatar
	QAT ISO31661Alpha3 = "QAT"
	// South Korea
	KOR ISO31661Alpha3 = "KOR"
	// Moldova
	MDA ISO31661Alpha3 = "MDA"
	// Romania
	ROU ISO31661Alpha3 = "ROU"
	// Russia
	RUS ISO31661Alpha3 = "RUS"
	// Rwanda
	RWA ISO31661Alpha3 = "RWA"
	// Réunion
	REU ISO31661Alpha3 = "REU"
	// St. Barthélemy
	BLM ISO31661Alpha3 = "BLM"
	// St. Helena
	SHN ISO31661Alpha3 = "SHN"
	// St. Kitts & Nevis
	KNA ISO31661Alpha3 = "KNA"
	// St. Lucia
	LCA ISO31661Alpha3 = "LCA"
	// St. Martin
	MAF ISO31661Alpha3 = "MAF"
	// St. Pierre & Miquelon
	SPM ISO31661Alpha3 = "SPM"
	// St. Vincent & Grenadines
	VCT ISO31661Alpha3 = "VCT"
	// Samoa
	WSM ISO31661Alpha3 = "WSM"
	// San Marino
	SMR ISO31661Alpha3 = "SMR"
	// São Tomé & Príncipe
	STP ISO31661Alpha3 = "STP"
	// Saudi Arabia
	SAU ISO31661Alpha3 = "SAU"
	// Senegal
	SEN ISO31661Alpha3 = "SEN"
	// Serbia
	SRB ISO31661Alpha3 = "SRB"
	// Seychelles
	SYC ISO31661Alpha3 = "SYC"
	// Sierra Leone
	SLE ISO31661Alpha3 = "SLE"
	// Singapore
	SGP ISO31661Alpha3 = "SGP"
	// Sint Maarten
	SXM ISO31661Alpha3 = "SXM"
	// Slovakia
	SVK ISO31661Alpha3 = "SVK"
	// Slovenia
	SVN ISO31661Alpha3 = "SVN"
	// Solomon Islands
	SLB ISO31661Alpha3 = "SLB"
	// Somalia
	SOM ISO31661Alpha3 = "SOM"
	// South Africa
	ZAF ISO31661Alpha3 = "ZAF"
	// South Georgia & South Sandwich Islands
	SGS ISO31661Alpha3 = "SGS"
	// South Sudan
	SSD ISO31661Alpha3 = "SSD"
	// Spain
	ESP ISO31661Alpha3 = "ESP"
	// Sri Lanka
	LKA ISO31661Alpha3 = "LKA"
	// Palestine
	PSE ISO31661Alpha3 = "PSE"
	// Sudan
	SDN ISO31661Alpha3 = "SDN"
	// Suriname
	SUR ISO31661Alpha3 = "SUR"
	// Svalbard & Jan Mayen
	SJM ISO31661Alpha3 = "SJM"
	// Swaziland
	SWZ ISO31661Alpha3 = "SWZ"
	// Sweden
	SWE ISO31661Alpha3 = "SWE"
	// Switzerland
	CHE ISO31661Alpha3 = "CHE"
	// Syria
	SYR ISO31661Alpha3 = "SYR"
	// Tajikistan
	TJK ISO31661Alpha3 = "TJK"
	// Thailand
	THA ISO31661Alpha3 = "THA"
	// Macedonia
	MKD ISO31661Alpha3 = "MKD"
	// Timor-Leste
	TLS ISO31661Alpha3 = "TLS"
	// Togo
	TGO ISO31661Alpha3 = "TGO"
	// Tokelau
	TKL ISO31661Alpha3 = "TKL"
	// Tonga
	TON ISO31661Alpha3 = "TON"
	// Trinidad & Tobago
	TTO ISO31661Alpha3 = "TTO"
	// Tunisia
	TUN ISO31661Alpha3 = "TUN"
	// Turkey
	TUR ISO31661Alpha3 = "TUR"
	// Turkmenistan
	TKM ISO31661Alpha3 = "TKM"
	// Turks & Caicos Islands
	TCA ISO31661Alpha3 = "TCA"
	// Tuvalu
	TUV ISO31661Alpha3 = "TUV"
	// Uganda
	UGA ISO31661Alpha3 = "UGA"
	// Ukraine
	UKR ISO31661Alpha3 = "UKR"
	// United Arab Emirates
	ARE ISO31661Alpha3 = "ARE"
	// UK
	GBR ISO31661Alpha3 = "GBR"
	// Tanzania
	TZA ISO31661Alpha3 = "TZA"
	// U.S. Outlying Islands
	UMI ISO31661Alpha3 = "UMI"
	// U.S. Virgin Islands
	VIR ISO31661Alpha3 = "VIR"
	// US
	USA ISO31661Alpha3 = "USA"
	// Uruguay
	URY ISO31661Alpha3 = "URY"
	// Uzbekistan
	UZB ISO31661Alpha3 = "UZB"
	// Vanuatu
	VUT ISO31661Alpha3 = "VUT"
	// Venezuela
	VEN ISO31661Alpha3 = "VEN"
	// Vietnam
	VNM ISO31661Alpha3 = "VNM"
	// Wallis & Futuna
	WLF ISO31661Alpha3 = "WLF"
	// Western Sahara
	ESH ISO31661Alpha3 = "ESH"
	// Yemen
	YEM ISO31661Alpha3 = "YEM"
	// Zambia
	ZMB ISO31661Alpha3 = "ZMB"
	// Zimbabwe
	ZWE ISO31661Alpha3 = "ZWE"
	// Åland Islands
	ALA ISO31661Alpha3 = "ALA"
)

var ValidAlpha3Codes = []ISO31661Alpha3{
	TWN,
	AFG,
	ALB,
	DZA,
	ASM,
	AND,
	AGO,
	AIA,
	ATA,
	ATG,
	ARG,
	ARM,
	ABW,
	AUS,
	AUT,
	AZE,
	BHS,
	BHR,
	BGD,
	BRB,
	BLR,
	BEL,
	BLZ,
	BEN,
	BMU,
	BTN,
	BOL,
	BES,
	BIH,
	BWA,
	BVT,
	BRA,
	IOT,
	VGB,
	BRN,
	BGR,
	BFA,
	BDI,
	CPV,
	KHM,
	CMR,
	CAN,
	CYM,
	CAF,
	TCD,
	CHL,
	CHN,
	HKG,
	MAC,
	CXR,
	CCK,
	COL,
	COM,
	COG,
	COK,
	CRI,
	HRV,
	CUB,
	CUW,
	CYP,
	CZE,
	CIV,
	PRK,
	COD,
	DNK,
	DJI,
	DMA,
	DOM,
	ECU,
	EGY,
	SLV,
	GNQ,
	ERI,
	EST,
	ETH,
	FLK,
	FRO,
	FJI,
	FIN,
	FRA,
	GUF,
	PYF,
	ATF,
	GAB,
	GMB,
	GEO,
	DEU,
	GHA,
	GIB,
	GRC,
	GRL,
	GRD,
	GLP,
	GUM,
	GTM,
	GGY,
	GIN,
	GNB,
	GUY,
	HTI,
	HMD,
	VAT,
	HND,
	HUN,
	ISL,
	IND,
	IDN,
	IRN,
	IRQ,
	IRL,
	IMN,
	ISR,
	ITA,
	JAM,
	JPN,
	JEY,
	JOR,
	KAZ,
	KEN,
	KIR,
	KWT,
	KGZ,
	LAO,
	LVA,
	LBN,
	LSO,
	LBR,
	LBY,
	LIE,
	LTU,
	LUX,
	MDG,
	MWI,
	MYS,
	MDV,
	MLI,
	MLT,
	MHL,
	MTQ,
	MRT,
	MUS,
	MYT,
	MEX,
	FSM,
	MCO,
	MNG,
	MNE,
	MSR,
	MAR,
	MOZ,
	MMR,
	NAM,
	NRU,
	NPL,
	NLD,
	NCL,
	NZL,
	NIC,
	NER,
	NGA,
	NIU,
	NFK,
	MNP,
	NOR,
	OMN,
	PAK,
	PLW,
	PAN,
	PNG,
	PRY,
	PER,
	PHL,
	PCN,
	POL,
	PRT,
	PRI,
	QAT,
	KOR,
	MDA,
	ROU,
	RUS,
	RWA,
	REU,
	BLM,
	SHN,
	KNA,
	LCA,
	MAF,
	SPM,
	VCT,
	WSM,
	SMR,
	STP,
	SAU,
	SEN,
	SRB,
	SYC,
	SLE,
	SGP,
	SXM,
	SVK,
	SVN,
	SLB,
	SOM,
	ZAF,
	SGS,
	SSD,
	ESP,
	LKA,
	PSE,
	SDN,
	SUR,
	SJM,
	SWZ,
	SWE,
	CHE,
	SYR,
	TJK,
	THA,
	MKD,
	TLS,
	TGO,
	TKL,
	TON,
	TTO,
	TUN,
	TUR,
	TKM,
	TCA,
	TUV,
	UGA,
	UKR,
	ARE,
	GBR,
	TZA,
	UMI,
	VIR,
	USA,
	URY,
	UZB,
	VUT,
	VEN,
	VNM,
	WLF,
	ESH,
	YEM,
	ZMB,
	ZWE,
	ALA,
}
