// Code generated by "make build"; DO NOT EDIT.

package iso3166

const (
	AF ISO31661Alpha2 = "Afghanistan"
	AX ISO31661Alpha2 = "Åland Islands"
	AL ISO31661Alpha2 = "Albania"
	DZ ISO31661Alpha2 = "Algeria"
	AS ISO31661Alpha2 = "American Samoa"
	AD ISO31661Alpha2 = "Andorra"
	AO ISO31661Alpha2 = "Angola"
	AI ISO31661Alpha2 = "Anguilla"
	AQ ISO31661Alpha2 = "Antarctica"
	AG ISO31661Alpha2 = "Antigua and Barbuda"
	AR ISO31661Alpha2 = "Argentina"
	AM ISO31661Alpha2 = "Armenia"
	AW ISO31661Alpha2 = "Aruba"
	AU ISO31661Alpha2 = "Australia"
	AT ISO31661Alpha2 = "Austria"
	AZ ISO31661Alpha2 = "Azerbaijan"
	BS ISO31661Alpha2 = "Bahamas"
	BH ISO31661Alpha2 = "Bahrain"
	BD ISO31661Alpha2 = "Bangladesh"
	BB ISO31661Alpha2 = "Barbados"
	BY ISO31661Alpha2 = "Belarus"
	BE ISO31661Alpha2 = "Belgium"
	BZ ISO31661Alpha2 = "Belize"
	BJ ISO31661Alpha2 = "Benin"
	BM ISO31661Alpha2 = "Bermuda"
	BT ISO31661Alpha2 = "Bhutan"
	BO ISO31661Alpha2 = "Bolivia, Plurinational State of"
	BQ ISO31661Alpha2 = "Bonaire, Sint Eustatius and Saba"
	BA ISO31661Alpha2 = "Bosnia and Herzegovina"
	BW ISO31661Alpha2 = "Botswana"
	BV ISO31661Alpha2 = "Bouvet Island"
	BR ISO31661Alpha2 = "Brazil"
	IO ISO31661Alpha2 = "British Indian Ocean Territory"
	BN ISO31661Alpha2 = "Brunei Darussalam"
	BG ISO31661Alpha2 = "Bulgaria"
	BF ISO31661Alpha2 = "Burkina Faso"
	BI ISO31661Alpha2 = "Burundi"
	KH ISO31661Alpha2 = "Cambodia"
	CM ISO31661Alpha2 = "Cameroon"
	CA ISO31661Alpha2 = "Canada"
	CV ISO31661Alpha2 = "Cape Verde"
	KY ISO31661Alpha2 = "Cayman Islands"
	CF ISO31661Alpha2 = "Central African Republic"
	TD ISO31661Alpha2 = "Chad"
	CL ISO31661Alpha2 = "Chile"
	CN ISO31661Alpha2 = "China"
	CX ISO31661Alpha2 = "Christmas Island"
	CC ISO31661Alpha2 = "Cocos (Keeling) Islands"
	CO ISO31661Alpha2 = "Colombia"
	KM ISO31661Alpha2 = "Comoros"
	CG ISO31661Alpha2 = "Congo"
	CD ISO31661Alpha2 = "Congo, the Democratic Republic of the"
	CK ISO31661Alpha2 = "Cook Islands"
	CR ISO31661Alpha2 = "Costa Rica"
	CI ISO31661Alpha2 = "Côte d'Ivoire"
	HR ISO31661Alpha2 = "Croatia"
	CU ISO31661Alpha2 = "Cuba"
	CW ISO31661Alpha2 = "Curaçao"
	CY ISO31661Alpha2 = "Cyprus"
	CZ ISO31661Alpha2 = "Czech Republic"
	DK ISO31661Alpha2 = "Denmark"
	DJ ISO31661Alpha2 = "Djibouti"
	DM ISO31661Alpha2 = "Dominica"
	DO ISO31661Alpha2 = "Dominican Republic"
	EC ISO31661Alpha2 = "Ecuador"
	EG ISO31661Alpha2 = "Egypt"
	SV ISO31661Alpha2 = "El Salvador"
	GQ ISO31661Alpha2 = "Equatorial Guinea"
	ER ISO31661Alpha2 = "Eritrea"
	EE ISO31661Alpha2 = "Estonia"
	ET ISO31661Alpha2 = "Ethiopia"
	FK ISO31661Alpha2 = "Falkland Islands (Malvinas)"
	FO ISO31661Alpha2 = "Faroe Islands"
	FJ ISO31661Alpha2 = "Fiji"
	FI ISO31661Alpha2 = "Finland"
	FR ISO31661Alpha2 = "France"
	GF ISO31661Alpha2 = "French Guiana"
	PF ISO31661Alpha2 = "French Polynesia"
	TF ISO31661Alpha2 = "French Southern Territories"
	GA ISO31661Alpha2 = "Gabon"
	GM ISO31661Alpha2 = "Gambia"
	GE ISO31661Alpha2 = "Georgia"
	DE ISO31661Alpha2 = "Germany"
	GH ISO31661Alpha2 = "Ghana"
	GI ISO31661Alpha2 = "Gibraltar"
	GR ISO31661Alpha2 = "Greece"
	GL ISO31661Alpha2 = "Greenland"
	GD ISO31661Alpha2 = "Grenada"
	GP ISO31661Alpha2 = "Guadeloupe"
	GU ISO31661Alpha2 = "Guam"
	GT ISO31661Alpha2 = "Guatemala"
	GG ISO31661Alpha2 = "Guernsey"
	GN ISO31661Alpha2 = "Guinea"
	GW ISO31661Alpha2 = "Guinea-Bissau"
	GY ISO31661Alpha2 = "Guyana"
	HT ISO31661Alpha2 = "Haiti"
	HM ISO31661Alpha2 = "Heard Island and McDonald Islands"
	VA ISO31661Alpha2 = "Holy See (Vatican City State)"
	HN ISO31661Alpha2 = "Honduras"
	HK ISO31661Alpha2 = "Hong Kong"
	HU ISO31661Alpha2 = "Hungary"
	IS ISO31661Alpha2 = "Iceland"
	IN ISO31661Alpha2 = "India"
	ID ISO31661Alpha2 = "Indonesia"
	IR ISO31661Alpha2 = "Iran, Islamic Republic of"
	IQ ISO31661Alpha2 = "Iraq"
	IE ISO31661Alpha2 = "Ireland"
	IM ISO31661Alpha2 = "Isle of Man"
	IL ISO31661Alpha2 = "Israel"
	IT ISO31661Alpha2 = "Italy"
	JM ISO31661Alpha2 = "Jamaica"
	JP ISO31661Alpha2 = "Japan"
	JE ISO31661Alpha2 = "Jersey"
	JO ISO31661Alpha2 = "Jordan"
	KZ ISO31661Alpha2 = "Kazakhstan"
	KE ISO31661Alpha2 = "Kenya"
	KI ISO31661Alpha2 = "Kiribati"
	KP ISO31661Alpha2 = "Korea, Democratic People's Republic of"
	KR ISO31661Alpha2 = "Korea, Republic of"
	KW ISO31661Alpha2 = "Kuwait"
	KG ISO31661Alpha2 = "Kyrgyzstan"
	LA ISO31661Alpha2 = "Lao People's Democratic Republic"
	LV ISO31661Alpha2 = "Latvia"
	LB ISO31661Alpha2 = "Lebanon"
	LS ISO31661Alpha2 = "Lesotho"
	LR ISO31661Alpha2 = "Liberia"
	LY ISO31661Alpha2 = "Libya"
	LI ISO31661Alpha2 = "Liechtenstein"
	LT ISO31661Alpha2 = "Lithuania"
	LU ISO31661Alpha2 = "Luxembourg"
	MO ISO31661Alpha2 = "Macao"
	MK ISO31661Alpha2 = "Macedonia, the Former Yugoslav Republic of"
	MG ISO31661Alpha2 = "Madagascar"
	MW ISO31661Alpha2 = "Malawi"
	MY ISO31661Alpha2 = "Malaysia"
	MV ISO31661Alpha2 = "Maldives"
	ML ISO31661Alpha2 = "Mali"
	MT ISO31661Alpha2 = "Malta"
	MH ISO31661Alpha2 = "Marshall Islands"
	MQ ISO31661Alpha2 = "Martinique"
	MR ISO31661Alpha2 = "Mauritania"
	MU ISO31661Alpha2 = "Mauritius"
	YT ISO31661Alpha2 = "Mayotte"
	MX ISO31661Alpha2 = "Mexico"
	FM ISO31661Alpha2 = "Micronesia, Federated States of"
	MD ISO31661Alpha2 = "Moldova, Republic of"
	MC ISO31661Alpha2 = "Monaco"
	MN ISO31661Alpha2 = "Mongolia"
	ME ISO31661Alpha2 = "Montenegro"
	MS ISO31661Alpha2 = "Montserrat"
	MA ISO31661Alpha2 = "Morocco"
	MZ ISO31661Alpha2 = "Mozambique"
	MM ISO31661Alpha2 = "Myanmar"
	NA ISO31661Alpha2 = "Namibia"
	NR ISO31661Alpha2 = "Nauru"
	NP ISO31661Alpha2 = "Nepal"
	NL ISO31661Alpha2 = "Netherlands"
	NC ISO31661Alpha2 = "New Caledonia"
	NZ ISO31661Alpha2 = "New Zealand"
	NI ISO31661Alpha2 = "Nicaragua"
	NE ISO31661Alpha2 = "Niger"
	NG ISO31661Alpha2 = "Nigeria"
	NU ISO31661Alpha2 = "Niue"
	NF ISO31661Alpha2 = "Norfolk Island"
	MP ISO31661Alpha2 = "Northern Mariana Islands"
	NO ISO31661Alpha2 = "Norway"
	OM ISO31661Alpha2 = "Oman"
	PK ISO31661Alpha2 = "Pakistan"
	PW ISO31661Alpha2 = "Palau"
	PS ISO31661Alpha2 = "Palestine, State of"
	PA ISO31661Alpha2 = "Panama"
	PG ISO31661Alpha2 = "Papua New Guinea"
	PY ISO31661Alpha2 = "Paraguay"
	PE ISO31661Alpha2 = "Peru"
	PH ISO31661Alpha2 = "Philippines"
	PN ISO31661Alpha2 = "Pitcairn"
	PL ISO31661Alpha2 = "Poland"
	PT ISO31661Alpha2 = "Portugal"
	PR ISO31661Alpha2 = "Puerto Rico"
	QA ISO31661Alpha2 = "Qatar"
	RE ISO31661Alpha2 = "Réunion"
	RO ISO31661Alpha2 = "Romania"
	RU ISO31661Alpha2 = "Russian Federation"
	RW ISO31661Alpha2 = "Rwanda"
	BL ISO31661Alpha2 = "Saint Barthélemy"
	SH ISO31661Alpha2 = "Saint Helena, Ascension and Tristan da Cunha"
	KN ISO31661Alpha2 = "Saint Kitts and Nevis"
	LC ISO31661Alpha2 = "Saint Lucia"
	MF ISO31661Alpha2 = "Saint Martin (French part)"
	PM ISO31661Alpha2 = "Saint Pierre and Miquelon"
	VC ISO31661Alpha2 = "Saint Vincent and the Grenadines"
	WS ISO31661Alpha2 = "Samoa"
	SM ISO31661Alpha2 = "San Marino"
	ST ISO31661Alpha2 = "Sao Tome and Principe"
	SA ISO31661Alpha2 = "Saudi Arabia"
	SN ISO31661Alpha2 = "Senegal"
	RS ISO31661Alpha2 = "Serbia"
	SC ISO31661Alpha2 = "Seychelles"
	SL ISO31661Alpha2 = "Sierra Leone"
	SG ISO31661Alpha2 = "Singapore"
	SX ISO31661Alpha2 = "Sint Maarten (Dutch part)"
	SK ISO31661Alpha2 = "Slovakia"
	SI ISO31661Alpha2 = "Slovenia"
	SB ISO31661Alpha2 = "Solomon Islands"
	SO ISO31661Alpha2 = "Somalia"
	ZA ISO31661Alpha2 = "South Africa"
	GS ISO31661Alpha2 = "South Georgia and the South Sandwich Islands"
	SS ISO31661Alpha2 = "South Sudan"
	ES ISO31661Alpha2 = "Spain"
	LK ISO31661Alpha2 = "Sri Lanka"
	SD ISO31661Alpha2 = "Sudan"
	SR ISO31661Alpha2 = "Suriname"
	SJ ISO31661Alpha2 = "Svalbard and Jan Mayen"
	SZ ISO31661Alpha2 = "Swaziland"
	SE ISO31661Alpha2 = "Sweden"
	CH ISO31661Alpha2 = "Switzerland"
	SY ISO31661Alpha2 = "Syrian Arab Republic"
	TW ISO31661Alpha2 = "Taiwan, Province of China"
	TJ ISO31661Alpha2 = "Tajikistan"
	TZ ISO31661Alpha2 = "Tanzania, United Republic of"
	TH ISO31661Alpha2 = "Thailand"
	TL ISO31661Alpha2 = "Timor-Leste"
	TG ISO31661Alpha2 = "Togo"
	TK ISO31661Alpha2 = "Tokelau"
	TO ISO31661Alpha2 = "Tonga"
	TT ISO31661Alpha2 = "Trinidad and Tobago"
	TN ISO31661Alpha2 = "Tunisia"
	TR ISO31661Alpha2 = "Turkey"
	TM ISO31661Alpha2 = "Turkmenistan"
	TC ISO31661Alpha2 = "Turks and Caicos Islands"
	TV ISO31661Alpha2 = "Tuvalu"
	UG ISO31661Alpha2 = "Uganda"
	UA ISO31661Alpha2 = "Ukraine"
	AE ISO31661Alpha2 = "United Arab Emirates"
	GB ISO31661Alpha2 = "United Kingdom"
	US ISO31661Alpha2 = "United States"
	UM ISO31661Alpha2 = "United States Minor Outlying Islands"
	UY ISO31661Alpha2 = "Uruguay"
	UZ ISO31661Alpha2 = "Uzbekistan"
	VU ISO31661Alpha2 = "Vanuatu"
	VE ISO31661Alpha2 = "Venezuela, Bolivarian Republic of"
	VN ISO31661Alpha2 = "Viet Nam"
	VG ISO31661Alpha2 = "Virgin Islands, British"
	VI ISO31661Alpha2 = "Virgin Islands, U.S."
	WF ISO31661Alpha2 = "Wallis and Futuna"
	EH ISO31661Alpha2 = "Western Sahara"
	YE ISO31661Alpha2 = "Yemen"
	ZM ISO31661Alpha2 = "Zambia"
	ZW ISO31661Alpha2 = "Zimbabwe"
)

type ISO31661Alpha2 string

var ValidCodes = []ISO31661Alpha2{
	AF,
	AX,
	AL,
	DZ,
	AS,
	AD,
	AO,
	AI,
	AQ,
	AG,
	AR,
	AM,
	AW,
	AU,
	AT,
	AZ,
	BS,
	BH,
	BD,
	BB,
	BY,
	BE,
	BZ,
	BJ,
	BM,
	BT,
	BO,
	BQ,
	BA,
	BW,
	BV,
	BR,
	IO,
	BN,
	BG,
	BF,
	BI,
	KH,
	CM,
	CA,
	CV,
	KY,
	CF,
	TD,
	CL,
	CN,
	CX,
	CC,
	CO,
	KM,
	CG,
	CD,
	CK,
	CR,
	CI,
	HR,
	CU,
	CW,
	CY,
	CZ,
	DK,
	DJ,
	DM,
	DO,
	EC,
	EG,
	SV,
	GQ,
	ER,
	EE,
	ET,
	FK,
	FO,
	FJ,
	FI,
	FR,
	GF,
	PF,
	TF,
	GA,
	GM,
	GE,
	DE,
	GH,
	GI,
	GR,
	GL,
	GD,
	GP,
	GU,
	GT,
	GG,
	GN,
	GW,
	GY,
	HT,
	HM,
	VA,
	HN,
	HK,
	HU,
	IS,
	IN,
	ID,
	IR,
	IQ,
	IE,
	IM,
	IL,
	IT,
	JM,
	JP,
	JE,
	JO,
	KZ,
	KE,
	KI,
	KP,
	KR,
	KW,
	KG,
	LA,
	LV,
	LB,
	LS,
	LR,
	LY,
	LI,
	LT,
	LU,
	MO,
	MK,
	MG,
	MW,
	MY,
	MV,
	ML,
	MT,
	MH,
	MQ,
	MR,
	MU,
	YT,
	MX,
	FM,
	MD,
	MC,
	MN,
	ME,
	MS,
	MA,
	MZ,
	MM,
	NA,
	NR,
	NP,
	NL,
	NC,
	NZ,
	NI,
	NE,
	NG,
	NU,
	NF,
	MP,
	NO,
	OM,
	PK,
	PW,
	PS,
	PA,
	PG,
	PY,
	PE,
	PH,
	PN,
	PL,
	PT,
	PR,
	QA,
	RE,
	RO,
	RU,
	RW,
	BL,
	SH,
	KN,
	LC,
	MF,
	PM,
	VC,
	WS,
	SM,
	ST,
	SA,
	SN,
	RS,
	SC,
	SL,
	SG,
	SX,
	SK,
	SI,
	SB,
	SO,
	ZA,
	GS,
	SS,
	ES,
	LK,
	SD,
	SR,
	SJ,
	SZ,
	SE,
	CH,
	SY,
	TW,
	TJ,
	TZ,
	TH,
	TL,
	TG,
	TK,
	TO,
	TT,
	TN,
	TR,
	TM,
	TC,
	TV,
	UG,
	UA,
	AE,
	GB,
	US,
	UM,
	UY,
	UZ,
	VU,
	VE,
	VN,
	VG,
	VI,
	WF,
	EH,
	YE,
	ZM,
	ZW,
}
